version: '3'

services:
  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.1
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2 # contains ingest & enrich
    container_name: elastic
    environment:
      - node.name=elastic
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elastic
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
#    image: docker.elastic.co/kibana/kibana-oss:7.2.1
    image: docker.elastic.co/kibana/kibana:7.2.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: "http://elastic:9200"
#      XPACK_SECURITY_ENABLED: "true"
    ports:
      - "5601:5601"
  logstash:
#    image: docker.elastic.co/logstash/logstash-oss:7.2.1
    image: docker.elastic.co/logstash/logstash:7.2.1
    container_name: logstash
    environment:
      ELASTICSEARCH_HOSTS: "http://elastic:9200"
#      XPACK_MONITORING_ELASTICSEARCH_HOSTS: "http://elastic:9200"
#      XPACK_MONITORING_ENABLED: "false"
